config/routes.rb
Rails.application.routes.draw do
  resources :instructors
  resources :subjects
  resources :courses
  resources :users
  resources :registrations
  resources :sessions
  resources :enrollments

  get 'instructors/import' => "instructors#my_import"
  get 'courses/import' => "courses#my_import"
  get 'subjects/import' => "subjects#my_import"
  
  get 'users/new'
  get 'static_pages/home'

  get "instructors", to: "instructors#show"
  get "courses", to: "courses#show"
  get "subjects", to: "subjects#show"

  get "sign_up", to: "registrations#new"
  post "sign_up", to:  "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  get 'search' => 'pages#show'


  root 'static_pages#home'
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
    <div class="col-xs-10">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-2">
        <% if logged_in? %>  
        
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search", search_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="dropdown" >
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" >
            Options
            </a>
          <ul class="dropdown-menu" >
            <li>
            <%= link_to "Instructors", instructors_path %>
            </li>
            <li>
            <%= link_to "Courses", courses_path %>
            </li>
            <li>
            <%= link_to "Subjects", subjects_path %>
            </li>
          </ul>
        </li>

        <% else %>
          <li class= "nav-itam">
          <%= link_to "Sign up", sign_up_path, class: "nav-link" %>
          </li>
          <li class= "nav-itam">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
      <% end %>
      </ul>
  </div>
</div>
</header>